name: "Keep sync your forks"
author: truexpixells
description: "Update your forks to their main repo"
inputs:
    source-url:
        description: "The source clone URL"
        required: true
    fork-url:
        description: "The fork git URL"
        required: true

branding:
    icon: "git-branch"
    color: blue
runs:
    using: "composite"
    steps:
        - name: Run
          shell: bash
          run: |
              if [ ! -d .cloneDir-source ]; then
                  git clone --bare "${{ inputs.source-url }}" ".cloneDir-source"
                  if [ ! -d .cloneDir-source ]; then
                     echo "::error The directory was not created, cloning must have failed.";
                     exit 1;
                  fi
                  cd ".cloneDir-source"
              else
                  cd ".cloneDir-source"
                  git fetch --all -p -P
              fi
              git push "${{ inputs.fork-url }}"
